name: BlockFreezer
main: blockfreezer\BlockFreezer
version: 1.1.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Control what blocks update in your worlds!
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/BlockFreezer
